name: ${NETWORK:-mainnet}

services:
  cardano-node:
    image: cardanofoundation/cardano-wallet:${WALLET_TAG}
    environment:
      CARDANO_NODE_SOCKET_PATH: /ipc/${NODE_SOCKET_NAME}
    networks:
      - cardano-node
    volumes:
      - ${NODE_DB}:/data
      - ${NODE_SOCKET_DIR}:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    entrypoint: []
    command: >
      cardano-node run --topology /configs/cardano/${NETWORK}/topology.json
        --database-path /data
        --socket-path /ipc/${NODE_SOCKET_NAME}
        --config /configs/cardano/${NETWORK}/config.json
        +RTS -N -A16m -qg -qb -RTS

  cardano-wallet:
    image: cardanofoundation/cardano-wallet:${WALLET_TAG}
    networks:
      - cardano-node
    volumes:
      - ${WALLET_DB}:/wallet-db
      - ${NODE_SOCKET_DIR}:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    ports:
      - ${WALLET_PORT}:8090
      - ${WALLET_UI_PORT}:8091
      - ${DEPOSIT_WALLET_UI_PORT}:8092
    entrypoint: []
    command: >
      cardano-wallet serve
        --node-socket /ipc/${NODE_SOCKET_NAME}
        --database /wallet-db
        --listen-address 0.0.0.0
        --ui-port 8091
        --ui-deposit-port 8092
        --testnet /configs/cardano/${NETWORK}/byron-genesis.json

  postgres:
    image: postgres:14.10-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    networks:
      - postgres
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_DIR}:/var/lib/postgresql/data
    restart: on-failure
    command:
      - -c
      - maintenance_work_mem=1GB
      - -c
      - max_parallel_maintenance_workers=4
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  cardano-db-sync:
    image: ghcr.io/intersectmbo/cardano-db-sync:13.3.0.0
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    networks:
      - cardano-node
      - postgres
    volumes:
      - ${DB_SYNC_DIR}:/var/lib/cexplorer
      - ${NODE_SOCKET_DIR}:/node-ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
networks:
  cardano-node: {}
  postgres: {}
